import { z } from 'zod'

export const updateSettingsSchema = z.object({
  distanceUnit: z.enum(['km', 'miles']).optional(),
  temperatureUnit: z.enum(['celsius', 'fahrenheit']).optional(),
  dashboardMapZoomPreset: z.enum(['street', 'district', 'city']).optional(),
  pricePerKwh: z.number().min(0).max(10).optional(),
  minTripDistanceKm: z.number().min(0).max(200).optional(),
  tripsInitialDisplayCount: z.number().int().min(1).max(200).optional(),
  chargesInitialDisplayCount: z.number().int().min(1).max(200).optional(),
  diagnosticsFreshnessWarnMin: z.number().int().min(1).max(180).optional(),
  diagnosticsFreshnessCriticalMin: z.number().int().min(2).max(360).optional(),
  diagnosticsBatteryDeltaWarnPct: z.number().min(0.1).max(20).optional(),
  diagnosticsBatteryDeltaCriticalPct: z.number().min(0.2).max(30).optional(),
  diagnosticsIdleWarnHours7d: z.number().min(0).max(168).optional(),
  diagnosticsIdleCriticalHours7d: z.number().min(0).max(168).optional(),
  currency: z.string().length(3).optional(),
  homeLatitude: z.number().optional(),
  homeLongitude: z.number().optional(),
  homeRadiusM: z.number().min(50).max(5000).optional(),
  timezone: z.string().optional(),
  ecoModeEnabled: z.boolean().optional(),
  mqttEnabled: z.boolean().optional(),
  mqttBroker: z.string().optional(),
  mqttPort: z.number().min(1).max(65535).optional(),
  mqttUsername: z.string().optional(),
  mqttPassword: z.string().optional(),
})
