ALTER TABLE "user_settings"
ADD COLUMN "batteryChemistry" TEXT NOT NULL DEFAULT 'nca',
ADD COLUMN "batteryNominalKwh" DOUBLE PRECISION,
ADD COLUMN "tirePressureTargetBar" DOUBLE PRECISION NOT NULL DEFAULT 2.9,
ADD COLUMN "tirePressureToleranceBar" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD COLUMN "maxDailyDrainPct" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
ADD COLUMN "maxRecommendedSocPct" INTEGER NOT NULL DEFAULT 90;
